### ISSUE TITLE
Update Cocoapod version

### ISSUE THREAD

**Issue by philprime** [readefries/RFISO8601DateTime#3]
Can you please create a new Cocoapod version off the last commit.

I added the pod without a version/branch defined, therefore it uses the latest release, but you have commits afterwards.

I will use the following for now:
 
`pod 'RFISO8601DateTime', :git => "https://github.com/readefries/RFISO8601DateTime", :branch => "master"`

**Comment by readefries** [comment]
Yes! I'll create a new version!

**Comment by readefries** [comment]
Version 3.0.0 is released which supports Swift 4
