### ISSUE TITLE
Unable to make tests passing on a CI environment.

### ISSUE THREAD

**Issue by alexandrekarst** [readefries/RFISO8601DateTime#5]
Hi Hindrik,

That's not really an issue with your project but more a question on a problem I face. I've integrated your library by directly adding the files of your library in my project. I've also copied the tests files.

Everything is running properly and the tests succeeded locally on my Mac. When I run your tests trough CircleCI, I face some errors (please see below).

Perhaps could you guide me on what could go wrong regarding the tests errors?

Thanks.
Alexandre.

```
MyProjectTests.ISO8601DateTimeTests
testCalendarDate, XCTAssertTrue failed - The day should be 21, not 20
/Users/distiller/project/MyProjectTests/Specs/RFISO8601/RFISO8601DateTimeTests.swift:46
```
        XCTAssertTrue(components.month == 1, String(format: "The month should be 1, not %d", components.month!))
        XCTAssertTrue(components.day == 21, String(format: "The day should be 21, not %d", components.day!))
    }
  ```

testCalendarMonth, XCTAssertTrue failed - The year should be 2016, not 2015
/Users/distiller/project/MyProjectTests/Specs/RFISO8601/RFISO8601DateTimeTests.swift:31
```

      XCTAssertTrue(components.year == 2016, String(format: "The year should be 2016, not %d", components.year!))
      XCTAssertTrue(components.month == 1, String(format: "The month should be 1, not %d", components.month!))
  ```

testCalendarMonth, XCTAssertTrue failed - The month should be 1, not 12
/Users/distiller/project/MyProjectTests/Specs/RFISO8601/RFISO8601DateTimeTests.swift:32
```
      XCTAssertTrue(components.year == 2016, String(format: "The year should be 2016, not %d", components.year!))
      XCTAssertTrue(components.month == 1, String(format: "The month should be 1, not %d", components.month!))
    }
  ```

testOrdinalDate, XCTAssertTrue failed - The day should be 21, not 20
/Users/distiller/project/MyProjectTests/Specs/RFISO8601/RFISO8601DateTimeTests.swift:59
```
      XCTAssertTrue(components.year == 2016, String(format: "The year should be 2016, not %d", components.year!))
      XCTAssertTrue(day == 21, String(format: "The day should be 21, not %d", day))
    }
  ```

testWeekDate, XCTAssertTrue failed - The day of the week should be 6, not 5
/Users/distiller/project/MyProjectTests/Specs/RFISO8601/RFISO8601DateTimeTests.swift:72
```
      XCTAssertTrue(components.weekOfYear == 3, String(format: "The week of the year should be 3, not %d", components.weekOfYear!))
      XCTAssertTrue(components.weekday == 6, String(format: "The day of the week should be 6, not %d", components.weekday!))
    }
  ```

testWeekOfTheYear, XCTAssertTrue failed - The week of the year should be 3, not 2
/Users/distiller/project/MyProjectTests/Specs/RFISO8601/RFISO8601DateTimeTests.swift:84
```
      XCTAssertTrue(components.year == 2016, String(format: "The year should be 2016, not %d", components.year!))
      XCTAssertTrue(components.weekOfYear == 3, String(format: "The week of the year should be 3, not %d", components.weekOfYear!))
    }
  ```
```

I'm using fastlane scan with these configurations:

```
bundle exec fastlane scan --formatter xcpretty-json-formatter
```

```
            SCAN_DEVICE: iPhone 8
            SCAN_OS: 11.2
            XCPRETTY_JSON_FILE_OUTPUT: xcodebuild.json
```

**Comment by readefries** [comment]
Hey Alexandre,

By only looking at assertions, I can't really help you.

Best regards Hindrik
